#!/bin/bash

usage () {
    echo "Användning: $(basename $0) on/off"
}

if [ $# -eq 1 ]; then
    if [ $1 == "on" ]; then
	xrandr --output VGA1 --auto && xrandr --output LVDS1 --off
    elif [ $1 == "off" ]; then
	xrandr --output VGA1 --off && xrandr --output LVDS1 --auto
    else
	usage
	exit 1
    fi
else
    usage
    exit 1
fi
